//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturasCobroMensual_03.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Factura_01Entities1 : DbContext
    {
        public Factura_01Entities1()
            : base("name=Factura_01Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adm> Adm { get; set; }
        public virtual DbSet<Año> Año { get; set; }
        public virtual DbSet<Casas> Casas { get; set; }
        public virtual DbSet<CobrosMensuales> CobrosMensuales { get; set; }
        public virtual DbSet<Meses> Meses { get; set; }
        public virtual DbSet<PagosRealizados> PagosRealizados { get; set; }
        public virtual DbSet<Residentes> Residentes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
