//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturasCobroMensual_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosRealizados
    {
        public int IDPago { get; set; }
        public Nullable<int> IDResidente { get; set; }
        public Nullable<int> IDCasas { get; set; }
        public Nullable<int> IDAtendidoPor { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IDMeses { get; set; }
        public Nullable<int> IDAño { get; set; }
        public string MesesPagoPrueba { get; set; }
    
        public virtual Adm Adm { get; set; }
        public virtual Año Año { get; set; }
        public virtual Casas Casas { get; set; }
        public virtual Meses Meses { get; set; }
        public virtual Residentes Residentes { get; set; }
    }
}
